/* hnsqr/src/kubernetes/autoscaler.rs */
//!▫~•◦-------------------------------‣
//! # HNSQR-Native Metrics Autoscaler & Shard Expansion Advisor
//!▫~•◦-------------------------------------------------------------------‣
//!
//! Evaluates search & write latency, ProofTree traversal load, exact SIMD evaluations,
//! remote cache miss rates, and queue delays to recommend horizontal learner scaling
//! and shard partitioning without causing endless Raft consensus churn.
/*▫~•◦------------------------------------------------------------------------------------‣
 * © 2026 ArcMoon Studios ◦ SPDX-License-Identifier MIT OR Apache-2.0 ◦ Author: Lord Xyn ✶
 *///•------------------------------------------------------------------------------------‣

use std::time::Instant;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};

/// Metric inputs for evaluating autoscaling decisions.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AutoscalerMetrics {
    pub query_queue_delay_ms: f64,
    pub certified_p99_ms: f64,
    pub exact_simd_evals_per_query: f64,
    pub proof_tree_traversal_cost_us: f64,
    pub remote_fetch_queue_depth: usize,
    pub cache_miss_rate: f64,
    pub cpu_utilization_ratio: f64,
    pub resident_vector_bytes: u64,
    pub leader_wal_fsync_utilization: f64,
    pub current_learners: u32,
    pub current_shards: u32,
}

/// Recommendations generated by the HNSQR native autoscaler.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoscalerRecommendation {
    pub desired_learners: u32,
    pub recommend_shard_split: bool,
    pub rationale: Vec<String>,
}

/// HNSQR Autoscaler Engine with stabilization windows and cooldown protection.
pub struct NativeAutoscaler {
    target_certified_p99_ms: f64,
    cooldown_seconds: u64,
    last_scale_event: RwLock<Option<Instant>>,
}

impl NativeAutoscaler {
    pub fn new(target_certified_p99_ms: f64, cooldown_seconds: u64) -> Self {
        Self {
            target_certified_p99_ms,
            cooldown_seconds,
            last_scale_event: RwLock::new(None),
        }
    }

    /// Evaluates current metrics and returns actionable scaling recommendations.
    pub fn evaluate(&self, metrics: &AutoscalerMetrics) -> AutoscalerRecommendation {
        let mut rationale = Vec::new();
        let mut desired_learners = metrics.current_learners;
        let mut recommend_shard_split = false;

        // Check if in cooldown period
        let in_cooldown = if let Some(last) = *self.last_scale_event.read() {
            last.elapsed().as_secs() < self.cooldown_seconds
        } else {
            false
        };

        // 1. Learner Scale-Out evaluation
        if metrics.certified_p99_ms > self.target_certified_p99_ms
            || metrics.query_queue_delay_ms > 10.0
            || metrics.cpu_utilization_ratio > 0.80
        {
            if !in_cooldown {
                desired_learners = metrics.current_learners + 1;
                rationale.push(format!(
                    "Scale out learners (p99 latency {:.2}ms > target {:.2}ms, queue delay {:.2}ms)",
                    metrics.certified_p99_ms, self.target_certified_p99_ms, metrics.query_queue_delay_ms
                ));
            } else {
                rationale.push("Scaling inhibited: stabilization cooldown active".to_string());
            }
        } else if metrics.cpu_utilization_ratio < 0.20 && metrics.current_learners > 1 && !in_cooldown {
            desired_learners = metrics.current_learners.saturating_sub(1);
            rationale.push(format!(
                "Scale in learners (low CPU utilization {:.1}%)",
                metrics.cpu_utilization_ratio * 100.0
            ));
        }

        // 2. Shard Expansion / Partitioning advisor
        if metrics.resident_vector_bytes > 500 * 1024 * 1024 * 1024 // > 500 GB
            || metrics.leader_wal_fsync_utilization > 0.85
        {
            recommend_shard_split = true;
            rationale.push(format!(
                "Recommend shard split: WAL fsync utilization {:.1}%, resident data {:.1} GB",
                metrics.leader_wal_fsync_utilization * 100.0,
                metrics.resident_vector_bytes as f64 / (1024.0 * 1024.0 * 1024.0)
            ));
        }

        if desired_learners != metrics.current_learners {
            *self.last_scale_event.write() = Some(Instant::now());
        }

        AutoscalerRecommendation {
            desired_learners,
            recommend_shard_split,
            rationale,
        }
    }
}
